const ORDER_STATUSES = {
  PENDING_CONFIRMATION: "pending_confirmation",
  AWAITING_CUSTOMER_UPDATE: "awaiting_customer_update",
  AWAITING_CUSTOMER_EDIT: "awaiting_customer_edit",
  AWAITING_ADDRESS: "awaiting_address",
  AWAITING_PAYMENT: "awaiting_payment",
  PAYMENT_REVIEW: "payment_review",
  CONFIRMED: "confirmed",
  PREPARING: "preparing",
  RIDER_DISPATCHED: "rider_dispatched",
  DELIVERED: "delivered",
  CANCELLED: "cancelled",
};

const ALL_ORDER_STATUSES = Object.values(ORDER_STATUSES);

const ACTIVE_ORDER_STATUSES = [
  ORDER_STATUSES.PENDING_CONFIRMATION,
  ORDER_STATUSES.AWAITING_CUSTOMER_UPDATE,
  ORDER_STATUSES.AWAITING_CUSTOMER_EDIT,
  ORDER_STATUSES.AWAITING_ADDRESS,
  ORDER_STATUSES.AWAITING_PAYMENT,
  ORDER_STATUSES.PAYMENT_REVIEW,
  ORDER_STATUSES.CONFIRMED,
  ORDER_STATUSES.PREPARING,
  ORDER_STATUSES.RIDER_DISPATCHED,
];

module.exports = {
  ORDER_STATUSES,
  ALL_ORDER_STATUSES,
  ACTIVE_ORDER_STATUSES,
};
